name: chat-dev

services:
  adminer:
    image: adminer:latest
    ports:
      - 8080:8080

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: chat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nats:
    image: nats:latest
    ports:
      - 4222:4222

volumes:
  postgres_data:
