name: chat

services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: api
    ports:
      - 8000:8000
    depends_on:
      postgres:
        condition: service_healthy
      nats:
        condition: service_started

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: chat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  nats:
    image: nats:latest
    container_name: nats

volumes:
  postgres_data:
