package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	graph1 "github.com/yahn1ukov/chat/apps/api/internal/gql/graph"
)

func (r *Resolver) Mutation() graph1.MutationResolver { return &mutationResolver{r} }

func (r *Resolver) Query() graph1.QueryResolver { return &queryResolver{r} }

func (r *Resolver) Subscription() graph1.SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
